import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
const BASE = process.env.DASH_URL ?? 'http://localhost:5174';
const OUT = '.data/shots';
mkdirSync(OUT, { recursive: true });
const b = await chromium.launch();
const p = await b.newContext({ viewport: { width: 1366, height: 900 }, deviceScaleFactor: 1 }).then((c) => c.newPage());
await p.goto(BASE, { waitUntil: 'networkidle' });
await p.locator('input[type=email]').fill('admin@conductor.local');
await p.locator('input[type=password]').fill('admin123');
await p.getByRole('button', { name: 'Sign in' }).click();
await p.getByRole('button', { name: 'Schedules' }).waitFor({ timeout: 10000 });
await p.waitForTimeout(800);
await p.screenshot({ path: `${OUT}/tasks.png` });
await p.getByRole('button', { name: 'Schedules' }).click();
await p.getByRole('button', { name: 'New schedule' }).click();
const freq = p.locator('select').filter({ has: p.locator('option', { hasText: 'Every few minutes' }) }).first();
await freq.selectOption({ label: 'Every week' });
await p.waitForTimeout(400);
await p.screenshot({ path: `${OUT}/schedules.png` });
await p.getByRole('button', { name: 'Insights' }).click();
await p.waitForTimeout(1200);
await p.screenshot({ path: `${OUT}/insights.png` });
await b.close();
console.log('saved tasks.png, schedules.png, insights.png');
